### ISSUE TITLE
感谢大佬的工作~~~

### ISSUE THREAD

**Issue by lihansunbai** [videomanagertools/scraper#2]
感谢大佬的工作~~~
我们的痛点都差不多。。。先Fork了。。。
希望我日后改动的部分能帮你解决一些问题

**Comment by fhyoga** [comment]
@lihansunbai 注意下操作是直接动文件的，没搞清楚各个操作前，先搞了个测试用的目录，数据无价小心操作

**Comment by lihansunbai** [comment]
所以要先上一个测试环境咯
