### ISSUE TITLE
建议在 .gitignore 中添加 package-lock.json 解决部署过程中的各种疑难杂症

### ISSUE THREAD

**Issue by lihansunbai** [videomanagertools/scraper#3]
RT～
在Ubuntu 和 MinGW 两个平台下测试了部署，部署过程中依赖问题容易报错。建议在 .gitignore 中添加 package-lock.json 方便各个平台的部署。

**Comment by fhyoga** [comment]
你说的部署是打package包吗，我刚刚跑通了CI，看下release。确实在linux和windows上打包会有问题，这个配置是从一个模版项目继承过来的，配置很多很乱，我还在理。如果你有时间可以尝试着做一下

**Comment by fhyoga** [comment]
https://travis-ci.org/videomanagertools/scraper/builds/588861983
windows下打包会被某个子进程卡住，打包成功了但是不能平滑退出build。
不知道为什么要分三个平台打包。我觉得一个平台打，应该可以直接打出可以运行在其他平台的package。这个有时间需要看下，最好只在linux环境打全平台的包。

**Comment by lihansunbai** [comment]
因为一开始作死的选了MinGW 在Windows 上安装部署，总是装不上才跳到Ubuntu 的。不过换了平台还是在安装的时候有点小问题～～～～

**Comment by fhyoga** [comment]
@lihansunbai 贴一下报错信息

**Comment by lihansunbai** [comment]
--------------------------------------------------------------------------------------------------------------------------------------
本次疑难杂症
--------------------------------------------------------------------------------------------------------------------------------------
npm install  后，npm start 无法启动，npm run dev启动后发现两个js 404了。
报错的信息贴在下面了～～～
另：需要网络代理的设置部分～～～

--------------------------------------------------------------------------------------------------------------------------------------
LOG
--------------------------------------------------------------------------------------------------------------------------------------
[15:46:04.724] [warn] APPIMAGE env is not defined, current application is not an AppImage
✖ ｢wdm｣:
ERROR in ./app/scraper/core/index.ts
Module not found: Error: Can't resolve '../javBus' in '/home/lee/CODE/scraper/app/scraper/core'
 @ ./app/scraper/core/index.ts 155:0-31 186:20-26
 @ ./app/containers/Home/HeaderContent/index.tsx
 @ ./app/containers/Home/index.tsx
 @ ./app/containers/App.tsx
 @ ./app/index.tsx
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.tsx

ERROR in /home/lee/CODE/scraper/app/scraper/core/index.ts
./app/scraper/core/index.ts
[tsl] ERROR in /home/lee/CODE/scraper/app/scraper/core/index.ts(4,20)
      TS2307: Cannot find module '../javBus'.
Not rewriting GET /dist/renderer.dev.js because the path includes a dot (.) character.
✖ ｢wdm｣:
ERROR in ./app/scraper/core/index.ts
Module not found: Error: Can't resolve '../javBus' in '/home/lee/CODE/scraper/app/scraper/core'
 @ ./app/scraper/core/index.ts 155:0-31 186:20-26
 @ ./app/containers/Home/HeaderContent/index.tsx
 @ ./app/containers/Home/index.tsx
 @ ./app/containers/App.tsx
 @ ./app/index.tsx
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.tsx

ERROR in /home/lee/CODE/scraper/app/scraper/core/index.ts
./app/scraper/core/index.ts
[tsl] ERROR in /home/lee/CODE/scraper/app/scraper/core/index.ts(4,20)
      TS2307: Cannot find module '../javBus'.
--------------------------------------------------------------------------------------------------------------------------------------

**Comment by fhyoga** [comment]
拉取master最新的代码试试

**Comment by lihansunbai** [comment]
今天又拉了master重新Install了，还是这个错误

**Comment by fhyoga** [comment]
删掉node_modules 重新install 或者使用yarn install 。
还不行就报下平台，node版本我需要复现
