### ISSUE TITLE
installation error under manjaro platform

### ISSUE THREAD

**Issue by aiyolo** [videomanagertools/scraper#4]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@4.2.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@4.2.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aiyolo/.npm/_logs/2019-09-27T16_32_17_845Z-debug.log

**Comment by fhyoga** [comment]
看起来像是Electron未正确安装，建议添加Electron的镜像源，删除node_modules重装

**Comment by aiyolo** [comment]
> 看起来像是Electron未正确安装，建议添加Electron的镜像源，删除node_modules重装

按照指示，出现了新错误
✖ ｢wdm｣: 
ERROR in ./app/scraper/core/index.ts
Module not found: Error: Can't resolve '../javBus' in '/home/aiyolo/Documents/scraper/app/scraper/core'
 @ ./app/scraper/core/index.ts 155:0-31 186:20-26
 @ ./app/containers/Home/HeaderContent/index.tsx
 @ ./app/containers/Home/index.tsx
 @ ./app/containers/App.tsx
 @ ./app/index.tsx
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.tsx

ERROR in /home/aiyolo/Documents/scraper/app/scraper/core/index.ts
./app/scraper/core/index.ts
[tsl] ERROR in /home/aiyolo/Documents/scraper/app/scraper/core/index.ts(4,20)
      TS2307: Cannot find module '../javBus'

**Comment by lihansunbai** [comment]
建议直接下载release 的版本，我也遇到过同样的问题

**Comment by aiyolo** [comment]
@lihansunbai release没有linux平台的安装包

**Comment by fhyoga** [comment]
![image](https://user-images.githubusercontent.com/20250430/65827664-3230bb80-e2c5-11e9-8602-94f93b90a1d8.png)

大小写错了，好像是这个原因吧。mac和windows上不区分大小写，你们试一下，我手边暂时没linux环境验证 @aiyolo @lihansunbai

**Comment by aiyolo** [comment]
@Dec-F 修改index.js文件后，npm start能启动
