### ISSUE TITLE
能否加入.nfo自定义格式选项？

### ISSUE THREAD

**Issue by toyqiu** [videomanagertools/scraper#7]
使用过程中发现.nfo中<art>标签内定义的封面都是javbus库的图片在线地址，但是削刮的同时把图片都已经下载到本地了。

我的想法是这样的，如果.nfo用的是图片在线地址，就没有必要再把图片下载下来。
既然抓了图片，能否提供一个自定义.nfo格式

<art>
        <poster>/no.-poster.jpg</poster>
        <fanart>/no.-fanart.jpg</fanart>
</art>

我个人因为使用jellyfin的关系，主页poster要求尺寸一般要手动ps剪切一下，所以倾向于.nfo能自定义到本地地址，那手动修改的工程量就没有那么大了。

谢谢！

![image](https://user-images.githubusercontent.com/479873/70618142-19da0700-1c4d-11ea-9c89-86e29b40c2b3.png)

**Comment by fhyoga** [comment]
jellyfin 本地图片的优先级高于nfo文件

可以测试一下，其实nfo中的art标签是作为一个backup使用的，也就是只有在媒体文件同级路径下没有poster图片是，才会读取nfo中art标签。
所以你提的需求只需要PS一下`poster.jpg`就可以了。

本地路径写到nfo中，会造成问题。比如你爬取信息时用SMB协议读取文件，那么你的文件路径会是这样`//NAS/Movies/BT-100-poster.jpg`。jellyfin读取这种路径肯定会出错的

如果你真的想把nfo变成本地路径（强烈建议不要），可以把jellyfin媒体库管理中NFO选项和元信息下载选项打开。jellyfin会把图片的本地路径写入nfo文件，但是会覆盖掉在线地址。这样你就不能再用其他软件读取元信息了，因为路径是相对jellyfin服务器的

**Comment by toyqiu** [comment]
> jellyfin 本地图片的优先级高于nfo文件
> 
> 可以测试一下，其实nfo中的art标签是作为一个backup使用的，也就是只有在媒体文件同级路径下没有poster图片是，才会读取nfo中art标签。
> 所以你提的需求只需要PS一下`poster.jpg`就可以了。
> 
> 本地路径写到nfo中，会造成问题。比如你爬取信息时用SMB协议读取文件，那么你的文件路径会是这样`//NAS/Movies/BT-100-poster.jpg`。jellyfin读取这种路径肯定会出错的
> 
> 如果你真的想把nfo变成本地路径（强烈建议不要），可以把jellyfin媒体库管理中NFO选项和元信息下载选项打开。jellyfin会把图片的本地路径写入nfo文件，但是会覆盖掉在线地址。这样你就不能再用其他软件读取元信息了，因为路径是相对jellyfin服务器的

相对路径不行吗？我把.nfo都改成  /no.xx-poster.jpg 了，效果如下。
![image](https://user-images.githubusercontent.com/479873/70629937-b14b5400-1c65-11ea-95b9-de6d5d657673.png)

开issue中的截图中，本地图片poster我是全部都改了的，但是只有改了.nfo文件的箭头中的3个显示的是poster。上图都变了是因为.nfo都改了的。

**Comment by fhyoga** [comment]
@toyqiu 本地有图片时，nfo文件中art标签是不生效的。也就是你把nfo文件删除，封面图也应该是正常的，你最好自己测试一下
